name: Auto publish

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Get package version
        uses: tyankatsu0105/read-package-version-actions@v1
        with: 
          path: packages/devui-vue
        id: package-version

      - name: Create a tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.package-version.outputs.version }}
          message: 'Release v${{ steps.package-version.outputs.version }}'
          token: ${{ secrets.GITHUB_TOKEN }}
